robot:
    interface: enp5s0f1
    joint_modules:
        motor_numbers: [0, 1, 2, 3]
        motor_constants: 0.025
        gear_ratios: 9.
        max_currents: 8.
        reverse_polarities: [
            true, true, true, true
        ]
        lower_joint_limits: [
            -0.9, -0.9, -0.9, -0.9
        ]
        upper_joint_limits: [
            0.9,  0.9,  0.9,  0.9
        ]
        max_joint_velocities: 5.
        safety_damping: 0.2
    imu:
        rotate_vector: [1, 2, 3]
        orientation_vector: [1, 2, 3, 4]
joint_calibrator:
    # Can be either POS, NEG, ALT or AUTO
    search_methods: [
      POS, POS, POS, POS
    ]
    position_offsets: [
       0, 0, 0,
      0
    ]
    calib_order: [1, 0, 0, 1, 0, 0, 1, 0]
    calib_pos: [
        0.0,  0.0, 0.0, 0.0
    ]
    Kp: 5.
    Kd: 0.05
    T: 1.
    dt: 0.001
